### ISSUE TITLE
Using WebUtility.UrlEncode seems to prevent from pulling jobs that are in side folders/views in jenkins

### ISSUE THREAD

**Issue by markoueis** [Narochno/Narochno.Jenkins#4]
I want to get a job at the following location for example:

job\Legacy\job\organzation\job\testrepo\job\develop

But because we encode the string, Narochno.Jenkins escapes the slashes with %2F. Then i get a 404 not found from jenkins.

**Comment by alanedwardes** [comment]
Hi @markoueis,

Yes that looks like a bug. There's a few things we can do:
- Let the consumer of `Narochno.Jenkins` deal with encoding from this point on, remove all implicit encoding from the client
- Formalise the "paths" as an args[] array on the methods, so your call becomes `GetJob('Legacy', 'job', 'organisation', ...)`
- Keep the one parameter, but encode everything aside from `/`

Which solution would you prefer from your application's point of view?

Cheers,

Alan

**Comment by markoueis** [comment]
Given that this is a rest call, I would expect the caller to deal with properly formulating the uri and encoding. I would favour option 1

**Comment by alanedwardes** [comment]
Hi @markoueis,

The encoding was removed in Narcohno.Jenkins 2.0.0, which is now on NuGet.

Cheers

**Comment by markoueis** [comment]
Thanks. This worked great!
